apiVersion: v1
data:
  # Base64 of the license file
  nexus-repo-license.lic:
kind: Secret
metadata:
  annotations:
    # Change these to whatever is used when doing helm install <release-name> <helm repo> -f values.yaml -n <namespace>
    # Create namespace with kubectl create namespace <namespace>
    meta.helm.sh/release-name: nxha
    meta.helm.sh/release-namespace: nexusns
  labels:
    # Required or else helm install fails
    app.kubernetes.io/managed-by: Helm
  # can change if values.yaml is changed to match
  name: nexus-repo-license.lic
  namespace: nexusns
type: Opaque
